import { choice, noul, score } from "@typesafe-ai/sdk";

export const decisionClassificationGuidance = [
  "REQUEST_ACTION means a direct interpersonal or transactional request that creates a concrete obligation for the connected account.",
  "Optional marketing calls to action such as shop, view, learn more, or unsubscribe are INFORM, not REQUEST_ACTION, and do not make action_required likely.",
  "A promotion expiry is not urgent unless the connected account already has a concrete obligation."
].join(" ");

export const decisionQuestions = {
  contentType: choice("Classify the primary content type of the email thread.", {
    CONVERSATION: "Human-to-human correspondence or discussion.",
    NEWSLETTER: "Recurring editorial or informational subscription.",
    PROMOTION: "Marketing, offer, campaign, or sales promotion.",
    NOTIFICATION: "Automated status or product notification.",
    INVOICE: "Invoice, bill, or payment request.",
    RECEIPT: "Receipt or confirmation of a completed transaction.",
    OTHER: "None of the listed types fits."
  }),
  communicationIntent: choice("Classify the sender's primary communication intent in the latest relevant message.", {
    QUESTION: "Asks for information or an answer.",
    REQUEST_ACTION: "A direct interpersonal or transactional request that creates a concrete obligation; exclude optional marketing calls to action such as shop, view, learn more, or unsubscribe.",
    REQUEST_MEETING: "Asks to arrange or confirm a meeting.",
    INFORM: "Shares information or an optional promotional call to action without creating a recipient obligation.",
    INTRODUCE: "Introduces people, organizations, or a new relationship.",
    UNKNOWN: "The intent is unclear or contradictory."
  }),
  isSubscription: noul("Is this email part of a mailing-list or subscription stream?"),
  isAutomatedSender: noul("Was this primarily generated by an automated sender or system?"),
  replyExpected: noul("Does the sender reasonably expect a reply from the connected account?"),
  actionRequired: noul("Does the connected account have a concrete non-reply obligation? Exclude optional marketing calls to action, sales offers, shop/view links, and unsubscribe links."),
  attachmentDependency: noul("Would deciding what to do require opening or interpreting an attachment?"),
  contradictoryThread: noul("Does the thread contain conflicting requests, states, or conclusions that make one answer unsafe?"),
  urgency: score("Score urgency for the connected account. A promotion expiry is not urgent unless the account already has a concrete obligation.", [
    "No time pressure.",
    "Low urgency; can wait.",
    "Medium urgency; should be handled soon.",
    "High urgency; explicit near-term deadline or material consequence."
  ])
} as const;
